# Header (especifica la versión de la plantilla y una descripción)
AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB Table to Store Characters"

# Define el nombre de la tabla, con un valor por defecto
Parameters:
  TableName:
    Type: String
    Default: Characters
    Description: DynamoDB Table Name

# Define el servicio a crear (una tabla DynamoDB en este caso)
Resources:
  # Configuración de la tabla: nombre, tipo de datos de los atributos usados en las claves, clave primaria y modo pago por solicitud (on-demand)
  CharactersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "${TableName}-${AWS::StackName}"
      AttributeDefinitions:
        - AttributeName: character_id
          AttributeType: S
      KeySchema:
        - AttributeName: character_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

# Valores que pueden ser accedidos fuera de la pila: nombre de la tabla y ARN (indentificador único de la tabla)
Outputs: 
  TableName:
    Description: DynamoDB Table Name
    Value: !Ref CharactersTable

  TableArn:
    Description: ARN DynamoDB Table
    Value: !GetAtt CharactersTable.Arn